config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions, :registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: :create
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :movies, only: [:index, :show] do
    resources :bookmarks, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :reviews
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :image
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, :comment, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5,
    message: "%{value} is not between 0 and 5" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    if params[:list_id]
      create_list
    else
      create_movie
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def list_bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
    # @comment = params[:bookmark][:comment]
    # @movie = Movie.find(params[:bookmark][:movie])
  end

  def movie_bookmark_params
    params.require(:bookmark).permit(:comment, :list_id)
    # @comment = params[:bookmark][:comment]
    # @movie = Movie.find(params[:bookmark][:movie])
  end

  def create_list
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(list_bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @review = Review.new
      @movies = Movie.all.order(:title)
      @movie = @bookmark.movie
      render 'lists/show'
    end
  end

  def create_movie
    @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new(movie_bookmark_params)
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      @lists = List.all.order(:name)
      @list = @bookmark.list
      render 'movies/show'
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @lists = List.all.order(:name)
  end

  def show
    @bookmark = Bookmark.new
    @movies = Movie.all.order(:title)
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url, :image)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query]
      @pagy, @movies = pagy(Movie.where("upper(title) LIKE '%#{params[:query].upcase}%'"), items: 30)
    else
      @pagy, @movies = pagy(Movie.all.order(:title), items: 30)
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @bookmark = Bookmark.new
    @lists = List.all.order(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      @movies = Movie.all.order(:title)
      render 'lists/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for([@list, @bookmark], wrapper: :inline_form, html: { class: 'form-inline d-flex align-items-start'}) do |f| %>
  <%= f.input :comment, input_html: { placeholder: 'Enter a comment'} %>
  <%= f.association :movie, collection: @movies, selected: (@movie.id if @movie), prompt: 'Select a movie', input_html: { id: 'bookmark-select', class: 'select2' } %>
  <%= f.button :submit, class: 'btn btn-outline-primary' %>
<% end -%>

app/views/bookmarks/_form_movie.html.erb
<%= simple_form_for([@movie, @bookmark], wrapper: :inline_form, html: { class: 'form-inline d-flex align-items-start'}) do |f| %>
  <%= f.input :comment, input_html: { placeholder: 'Enter a comment'} %>
  <%= f.association :list, collection: @lists, selected: (@list.id if @list), prompt: 'Select a list', input_html: { id: 'bookmark-select', class: 'select2' } %>
  <%= f.button :submit, class: 'btn btn-outline-primary' %>
<% end -%>

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-10">
      <h1>Add a Bookmark</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to lists_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Lists", lists_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a list", new_list_path, class: "btn btn-outline-success ml-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class: "btn btn-outline-secondary ml-3" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle ml-3", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-danger dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary ml-3" %>
        </li>
      <% end -%>

    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, class: 'btn btn-outline-primary' %>
<% end -%>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80
);">
  <div class="container">
    <h1 class="text-center">Save any kind of movies!</h1>
    <p></p>
  </div>
</div>
<div class="container mt-3">
  <% if user_signed_in? %>
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-between mb-3">
      <h2>My Lists</h2>
      <%= link_to 'Create a new list', new_list_path, class: 'btn btn-outline-success' %>

      </div>
      <hr>
      <div class="cards">
        <% if @lists.empty? %>
        <p>No lists yet!</p>
        <% end -%>
        <% @lists.each do |list| %>
          <%= link_to list_path(list) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.image.attached? ? cl_image_path(list.image.key) : list.image_url %>)">
                <div class="num-film">
                  <h6><%= list.bookmarks.count %> movie(s)</h6>
                </div>
              <%= list.name %>
            </div>
          <% end -%>
        <% end -%>
      </div>
    </div>
  </div>
  <% else %>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card p-3">
          <h3 class="text-center">Please <%= link_to 'Login', new_user_session_path %> or <%= link_to 'Signup', new_user_registration_path %> to access the application</h3>
        </div>
      </div>
    </div>
  <% end -%>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1>Create a List</h1>
      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.image.attached? ? cl_image_path(@list.image.key) : @list.image_url %>);">
  <div class="num-film">
    <%= @list.bookmarks.count %> movie(s)
  </div>
  <div class="container">
    <h1 class="text-center"><%= @list.name %></h1>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-10">
          <h5>Add a movie</h5>
          <%= render 'bookmarks/form' %>

    </div>
  </div>
  <hr>
  <div class="cards mt-3">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="d-flex align-items-stretch">
        <div class="card-movie">
          <img src="<%= bookmark.movie.poster_url %>" />
          <div class="card-movie-infos">
            <div>
              <h2><%= link_to bookmark.movie.title, movie_path(bookmark.movie) %>  <%= icon('far','star', class: 'text-warning') * bookmark.movie.rating %></h2>
              <p><%= bookmark.movie.overview.truncate(150, separator: ' ') %></p>
              <br>
              <p>
                <%= icon('far', 'comment') %>
                <%= bookmark.comment %>
              </p>
            </div>
            <h2 class="card-movie-pricing"><%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }, class:'text-danger' %></h2>
          </div>
        </div>
      </div>
    <% end -%>
  </div>
  <hr>
  <div class="row mt-3">
    <div class="col-7">
      <h3>Reviews</h3>
      <% @list.reviews.order('created_at DESC').each do |review| %>
        <p><%= icon('far','star', class: 'text-warning') * review.rating %> <em><small><%= distance_of_time_in_words_to_now(review.created_at) %> ago</small></em></p>
        <p><%= review.comment %></p>
        <hr>
      <% end -%>
    </div>
    <div class="col-5">
      <div class="card p-3">
        <%= render 'reviews/form' %>
      </div>

    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1>Movies available</h1>

  <form class="form-inline my-2 my-lg-0 mr-2">
    <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
  <hr>
  <%== pagy_bootstrap_nav(@pagy) %>
  <div class="cards mt-3">
    <% @movies.each do |movie| %>
      <div class="d-flex align-items-stretch">
        <div class="card-movie">
          <img src="<%= movie.poster_url %>" />
          <div class="card-movie-infos">
            <div>
              <%= link_to movie_path(movie) do %>
                <h2><%= movie.title %>  <%= icon('far','star', class: 'text-warning') * movie.rating %></h2>
              <% end -%>
              <p><%= movie.overview.truncate(150, separator: ' ') %></p>
              <br>
            </div>
          </div>
        </div>
      </div>
    <% end -%>
  </div>
</div>

app/views/movies/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @movie.poster_url %>);">
  <div class="container">
    <h1 class="text-center"><%= @movie.title %></h1>
  </div>
</div>

<div class="container pt-3">
  <div class="row">
    <div class="col-10">
          <h5>Add to a list</h5>
          <%= render 'bookmarks/form_movie' %>
    </div>
  </div>
  <hr>
  <h3>Rating: <%= icon('far','star', class: 'text-warning') * @movie.rating %></h3>
  <h3>Description:</h3>
  <p><%= @movie.overview %></p>
  <p><%= link_to 'Back', :back, class:'btn btn-outline-primary' %></p>
</div>

app/views/reviews/_form.html.erb
<h5>Add a review</h5>
<%= simple_form_for([@list, @review]) do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: (1..5).to_a %>
  <%= f.button :submit, class: 'btn btn-outline-primary' %>
<% end -%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>